name: dsenum
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python>=3.7
  - sympy
  - scipy
  - matplotlib
  - joblib
  - tqdm
  - pip:
    - numpy==1.18.3
    - pymatgen>=2020.4.29
